name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: summary.tex
      - name: Upload Artifact
        uses: actions/upload-artifact@1.0.0
        with:
          name: Summary.pdf
          path: summary.pdf
